apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app1
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject-secret-bucket: 'secret/crossplane-system/application2/dev/bucket'
        vault.hashicorp.com/agent-inject-template-bucket: |
          {{- with secret "secret/crossplane-system/application2/dev/bucket" -}}
          bucket name: {{ .Data.data.endpoint }} -- region: {{ .Data.data.region }}
          {{- end -}}
