apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: provider-aws-config
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::259950518779:role/crossplane-provider-aws
