apiVersion: awsblueprints.io/v1alpha1
kind: Function
metadata:
  name: test-container-lambda
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  compositionSelector:
    matchLabels:
      awsblueprints.io/provider: aws-jet
      awsblueprints.io/environment: dev
  resourceConfig:
    providerConfigName: aws-provider-config
    jetProviderConfigName: jet-aws-provider-config
    region: us-west-2
  imageUri: 833162080385.dkr.ecr.us-west-2.amazonaws.com/dummy:0.0.1
  permissionsBoundaryArn: arn:aws:iam::833162080385:policy/crossplaneBoundary
  