apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nabuskey/argo-crossplane-vault.git
    targetRevision: HEAD
    path: kustomize
  destination:
    server: https://kubernetes.default.svc
    namespace: application2
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
