apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application1
  namespace: argocd
spec:
  project: application-team
  source:
    repoURL: https://github.com/nabuskey/argo-crossplane-vault.git
    targetRevision: HEAD
    path: application2/dev/
  destination:
    server: https://kubernetes.default.svc
    namespace: application2
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
