apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: application-team
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: application project
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  clusterResourceBlacklist:
  - group: 'awsblueprints.io'
    kind: 'X*'
  sourceRepos:
  - '*'
  destinations:
  - namespace: "*"
    server: "*"
