apiVersion: v1
kind: Secret
metadata:
  name: vault
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: hashicorp
  url: https://helm.releases.hashicorp.com
  type: helm
