apiVersion: v2
name: crossplane-installation
description: A Helm chart for crossplane on argocd
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name: crossplane
  version: 1.7.0
  repository: https://charts.crossplane.io/stable
